### ISSUE TITLE
Implement Functionality In ValidationManager To Validate KomodoObjects

### ISSUE THREAD

**Issue by elvisisking** [Teiid-Designer/komodo#115]
The `ValidationManager` API should be improved to handle the validation of one or more objects. The `ValidationManager` should collect, and then evaluate, all the applicable rules for each `KomodoObject`. The ability to cancel validation by using a progress monitor should be possible.

**Comment by mdrillin** [comment]
closing this issue - the title has been fulfilled.  I will open a separate issue for the 'cancel validation' feature, since it has not yet been implemented.
