### ISSUE TITLE
Filter out non-teiid properties & nodes with jcr and mmcore prefixes

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#120]
When using "property list" command I'm seeing jcr & mmcore prefixed properties. Need to filter the JCR-related properties in the CLI and maybe just remove the mmcore:, vdb:, ddl:, teiidddl: type prefixes

     jcr:mixinTypes           jcr:mixinTypes=[{http://www.modeshape.org/ddl/teiid/1.0}createTable]
     jcr:primaryType          jcr:primaryType={http://www.jcp.org/jcr/nt/1.0}unstructured
     jcr:uuid                 jcr:uuid=d593e7cc-d7a5-483d-93ca-721b3f528a16

     mmcore:modelType         mmcore:modelType=PHYSICAL

**Comment by elvisisking** [comment]
Hey @phantomjinx and @blafond , is it OK if I work this one? This is related to the getChildren work I am doing.

**Comment by phantomjinx** [comment]
On 27 April 2015 11:48:39 GMT+01:00, Daniel Florian <notifications@github.com> wrote:
>Hey @phantomjinx and @blafond , is it OK if I work this one? This is
>related to the getChildren work I am doing.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Teiid-Designer/komodo/issues/120#issuecomment-96606339

Sure.

**Comment by elvisisking** [comment]
Closed by #136
