### ISSUE TITLE
Tab Completion doesn't work in Eclipse Komodo Shell

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#123]
- Hitting tab does not display anything in the eclipse launched komodo shell

**Comment by asajigithub** [comment]
~~~
[tko:workspace] > 
cd        delete    import    navigate  property  rename    useTeiid  
create    export    list      play      record    status    
[tko:workspace] > import 
~~~
@mdrillin 
I tried "tab" and saw the above list of commands
and on pressing "i" I did see import getting listed/sleted as above  . Is that what you meant as well or Iam seeing this differently .

**Comment by mdrillin** [comment]
@asajigithub 
The tab completion does work if you install the zip locally and are running from a terminal window.  I'm referring to running the shell in eclipse for development.  In eclipse, we have a launcher definition - launches a workspace window and from there you can run 'KomodoConsole' in consoles.  The tabCompletion doesnt work properly in this dev environment.

**Comment by mdrillin** [comment]
Im closing this, since tab completion debugging is not possible using the eclipse launcher.  To debug tab completion:
- build and unzip the cli kit locally
- edit komodo.sh and uncomment the JAVA_OPTS near the top of the script
- launch komodo.sh from command line, then connect a remote eclipse debug session to port 8787
