### ISSUE TITLE
Provide means for each object type to expose a getAllowedChildTypes() method

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#124]
The CLI's "create" action needs a way to determine what child object types are allowed for a given object.

VDB's, for instance, allow data roles, translator overrides, models and file entry object types.

Models allow tables, procedures, functions, views, etc.

So for instance, if a user is at a model node and types "create <tab>" they should see:
    allowed types>  table, view, storedProcedure, userDefinedFunction, pushdownFunction, virtualProcedure

**Comment by elvisisking** [comment]
Closed by #139
