### ISSUE TITLE
Need to add property desrciptors for VDB elements that support specific <property> elements

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#125]
The <vdb> element in a vdb manifest supports a number of specific properties. Some defined as below:
    name="query-timeout" value="256000"
    name="allowed-languages" value="java, pascal"
    name="security-domain" value="custom-security"
    name="gss-pattern" value="%abc&amp;a-b"
    name="password-pattern" value="$xyz1-9"
    name="authentication-type" value="USERPASSWORD"

Need to somehow create property descriptors for these specific properties so a UI can access them, present the "keys" to the user so they can set these specific properties.

The following elements support 0-man <property> elements:   vdb, model, translator and entry

Note that translator property descriptors may be available and accessed from the Teiid server. Only "overridden" or custom/user-defined properties need to be defined in the VDB.

**Comment by elvisisking** [comment]
Closed by #142
