### ISSUE TITLE
WorkspaceManager RepositoryObserver Listener

### ISSUE THREAD

**Issue by elvisisking** [Teiid-Designer/komodo#138]
In the constructor of `WorkspaceManager`, we are creating a `RepositoryObserver`. I think this listener gets notified of **every** repository event. A couple questions:

- If the repository is not reachable, will events even be generated for this listener to handle?

- Since `WorkspaceManager` is now just another `KomodoObject`, should we be caching them at all?

Seems like we might be able to get rid of this listener. Wdyt?

**Comment by phantomjinx** [comment]
The observer is essential for disposing of workspacemanager instance if the respository it deals with shutsdown. This is apparent in the tests where the same repository (with id) is used in multiple tests and the workspacemanager is cached. Whether is should be cached as a singleton instance is questionable. However, not sure why the manager now has to be a komodo object either.

**Comment by elvisisking** [comment]
The reason for making `WorkspaceManager` a `RelationalObject` is twofold:

- to make the `KomodoObject` API directly available, and
- to have its children be resolved to their strong, relational type.

I was wrong about the `RepositoryObserver`. For some reason I thought that was a listener to a JCR repository. That all looks good.
