### ISSUE TITLE
Standard Statement Options Should Appear As If They Were Properties

### ISSUE THREAD

**Issue by elvisisking** [Teiid-Designer/komodo#140]
It would be nice if the property-related methods (like `getPropertyName`, `getProperty`, `setProperty`, `hasProperty`, etc.), included/worked with the statement options.

**Comment by blafond** [comment]
You mean add those same methods to the StatementOptionImpl.java?

**Comment by elvisisking** [comment]
No. I was thinking that those methods I mentioned earlier would also work with the statement options. So for instance: Column.getPropertyNames() would return "NAMEINSOURCE" as one of the property names. Also, Column.setProperty("NAMEINSOURCE", "blah") would, underneath the hood, set the statement option. Is that something we should do @blafond ?

**Comment by blafond** [comment]
From a user/relational object perspective, most of these "OPTIONS" are really properties. So I agree. The Column object however, has a more specific setNameInSource() get/sets too, which ends up calling Column.setProperty("NAMEINSOURCE", "blah")... I think

**Comment by elvisisking** [comment]
No. Options are actually child nodes not properties. So the Column.setNameInSource actually calls setStatementOption. What this issue would do is allow the generic KomodoObject.setProperty to be used to set the options as well. Column would override the setProperty method to make it happen.

**Comment by blafond** [comment]
k... I stand corrected :)  and I agree with your plan.

**Comment by elvisisking** [comment]
Closed by #150
