### ISSUE TITLE
CLI commands for creating PKs, ResultSets, etc need further investigation

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#149]
Currently in the CLI, the following command can be issued to create a PK
- create PrimaryKey PK1
Need more thought into PKs and some other objects (like ResultSets) that are not really considered 'children' nodes.  For example maybe they should be supported with a SET command instead of (or in addition to)

Also currently CREATE allows creation of multiple PKs.  Need to improve the validation in CreateCommand to disallow creating more than one.  Same goes for other similar objects

**Comment by elvisisking** [comment]
Work done in #146

**Comment by elvisisking** [comment]
See #175 for a start on this. Still have to implement removing table constraint columns and foreign keys. Also need to show the reference columns as paths instead of UUIDs.

**Comment by mdrillin** [comment]
Dan addressed this with PR #234
