### ISSUE TITLE
Allow for specific relational properties (Cardinality, Precision, etc) that require a value greater than an int type can handle

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#161]
Java int supports values of –2,147,483,648 to 2,147,483,647.

Table cardinality can exceed 2,147,483,647. So we need to be able to handle a value much larger than 2,147,483,647.  In this case changing to "long" java type would work.  

long will take you up to 9,223,372,036,854,775,807 = 2^63 - 1. Once you need values over that, you can either look into BigInteger or just use a floating point number like double.

We just need to account for larger values and not assume "int" java type.

**Comment by mdrillin** [comment]
This was addressed with PR#233, closing
