### ISSUE TITLE
cli hangs when setting property to same value as its current

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#207]
There is an issue setting a property, when the property value is the same as its current value.

- in cli, create a new VDB
- cd into the VDB, then do "set property version 1".  The command does not return.
- "set property version 2" succeeds, but if you then try "set property version 2" again - it hangs.

**Comment by elvisisking** [comment]
After the session is saved it does not appear like we are getting an event saying that the sequencer is finished. An easy way to duplicate this issue is to duplicate line 6 in `setCommand3.txt` and then run `SetCommandTest.testSetProperty3()`.

**Comment by mdrillin** [comment]
I have reproduced and have done some debugging.  KSequencers registers itself as an ObservationManager event listener.  The onEvent method invocation in KSequencers is what triggers 'notifySequencerComplete'.  However, for this case no events are generated - so no onEvent and as a result no notifySequencerComplete happens.

I need to consult with you Dan for resolution.  Should ModeshapeEngineThread.commitSession somehow determine that the pending changes will not result in any events?

**Comment by phantomjinx** [comment]
Created a PR with a possible solution. Seems modeshape does not check the property value is actually changing before adding the node affected to the session's change cache. Thus, we end up with the perverse situation that the session has pending changes but does not actually do anything. The PR checks the current value against the new value and only changes if different.

https://github.com/Teiid-Designer/komodo/pull/219

**Comment by mdrillin** [comment]
Looks good, merged PR
