### ISSUE TITLE
cli - need a way to create custom properties for an object

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#209]
- I dont think there is a way currently to create custom properties - we should allow the user to create custom properties
- I believe this applies to all objects
- It appears that if a dynamic vdb contains custom properties, they are created on import.  For example, I have a dynamic VDB with translator containing the property 'supportsFullOuterJoins false'.  It is created on import, but I cant create a new property with that name from scratch in the cli.

**Comment by elvisisking** [comment]
Fixed by #226
