### ISSUE TITLE
File (Script) drive building a VDB

### ISSUE THREAD

**Issue by vhalbert** [Teiid-Designer/komodo#223]
it would be (almost necessary) great to be able to define what goes into the VDB (roles, translators to use, translator overrides etc) in a file that can be provided

**Comment by mdrillin** [comment]
We have some examples at https://github.com/Teiid-Designer/teiid-designer-samples/blob/master/cli/more-examples.md  

The PartsVDB is the most detailed of the script files.  We will continue to add more examples as we build out the cli.

**Comment by vhalbert** [comment]
I think the clients expect the scripts to be more 1 full statement at a time.  Example:

Create foreign table (
columna ...
columnb...
)

**Comment by mdrillin** [comment]
I believe this is a duplicate of #113 which has to do with supporting ddl creates
