### ISSUE TITLE
cli - remove unused messages and other code

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#265]
On refactor, there are some resulting messages and possibly other methods that are unused and need to be removed.  (One option to detect is http://www.ucdetector.org)

**Comment by elvisisking** [comment]
As an example, `RelationalShellCommand`'s `getMessage` and `getWorkspaceMessage` both are using the same message bundle. The properties file in `org.komodo.relational.command.commands` is probably not being used and should be. There are duplicate messages in this properties file and the one in the `workspace` package.

**Comment by mdrillin** [comment]
closing - the request was merged.
