### ISSUE TITLE
cli - improve object properties display

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#278]
- currently we show object properties displayed as name-value pairs.  If the value is not set it just shows <no value>, however a lot of properties have defaults.  We should incorporate the defaults into the display - maybe show it with a different color if possible
- password property values (for example on the Teiid object) are show clearText.  We should detect and mask the password values on display

**Comment by elvisisking** [comment]
See #325 and #326 which handle displaying statement option default values in the show commands.

**Comment by elvisisking** [comment]
The masking of property values like passwords is being worked in issue #335 .
