### ISSUE TITLE
DefaultLabelProvider doens't return NULL for invalid paths

### ISSUE THREAD

**Issue by elfilip** [Teiid-Designer/komodo#316]
It causes wrong behavior of cd, list, rename.. commands

How to reproduce: 1. Remove jars which related to relational commands from the classpath
                              2. Execute command cd invalidPath
                              3. No error message is displayed, current context is probably in inconsistent state

RelationalLabelProvider works OK.

Goal is to redesign DefaultLabelProvider and  RelationalLabelProvider to remove duplicate code and port the working solution from RelationalLabelProvider into DefaultLabelProvider.

**Comment by elvisisking** [comment]
Closed by #329 and #330
