### ISSUE TITLE
Add a feature that can import dynamic vdb.xml files into the workspace and maybe a library location

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#57]
Migrating existing VDB artifacts, and dynamic vdbs in particular to a Komodo workspace will require an import capability. This would function similar to the ddl import feature, but load an xml file instead.  The VDB, DDL and SQL sequencers should handle the full parsing of this VDB.xml file.

* May want to expand this to handle VDB archives containing vdb.xml (manifest) and DDL model files.
* Teiid Designer will handle converting EMF/XMI model VDB's to DDL vdbs.

**Comment by phantomjinx** [comment]
https://github.com/Teiid-Designer/komodo/pull/60

**Comment by mdrillin** [comment]
closing after discussing with Barry - we've covered the vdb import and export.  Can address any other issues as the arise
