### ISSUE TITLE
Add option to properly format (indent) exported VDB manifest and DDL

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#67]
VdbNodeVisitor and DdlNodeVisitor classes do some formatting, but not enought.

Viewing the exported vdb.xml string containing DDL would benefit from propery new-line breaks and tabbing to correspond to the VDB schema element hiearchy.

**Comment by mdrillin** [comment]
The formatting has been improved.  We can address further formatting of the SQL in the future.
