### ISSUE TITLE
Create enum constants for possible Relational Object types and utility method for wrapping instanceof check to return integer type

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#70]
Would be nice to have a universal/core way to identify KO types in any UI or editor. I've got a RelationalIdentifier class which does instanceof checks and returns an integer type value defined in my own UI constants file.

see: https://github.com/blafond/komodo/blob/master/plugins/org.komodo.eclipse.workspace/src/org/komodo/eclipse/workspace/CoreConstants.java
see: https://github.com/blafond/komodo/blob/master/plugins/org.komodo.eclipse.workspace/src/org/komodo/eclipse/workspace/util/RelationalIdentifier.java

**Comment by elvisisking** [comment]
What if we define a constant like this in each strong typed `KomodoObject` interface (here's the one that AccessPattern would have):
```
int TYPE_ID = AccessPattern.class.hashCode();
```

This constant would work in a `switch` statement (though a `String` will also work if we just want to use the classname).

Then In each impl class we would have this:
```
    /**
     * {@inheritDoc}
     *
     * @see org.komodo.repository.ObjectImpl#getTypeId()
     */
    @Override
    public int getTypeId() {
        return TYPE_ID;
    }
```

Then code like this could be written:
```
switch(kobject.getTypeId()) {
    case AccessPattern.TYPE_ID ...
    case Model.TYPE_ID ...
    ...
}
```
wdyt?

**Comment by blafond** [comment]
That would work too.  Wasn't sure if we wanted to define any of these "TYPE" constants in a plugin above komodo.relational anyway.  Basically it's cleaner than instanceof and works with interfaces

**Comment by phantomjinx** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Am currently implementing something just like this.

On 19/02/15 20:19, Daniel Florian wrote:
> What if we define a constant like this in each strong typed |KomodoObject| interface (here's 
> the one that AccessPattern would have):
> 
> |int TYPE_ID = AccessPattern.class.hashCode(); |
> 
> This constant would work in a |switch| statement (though a |String| will also work if we just 
> want to use the classname).
> 
> Then In each impl class we would have this:
> 
> |    /** * {@inheritDoc} * * @see org.komodo.repository.ObjectImpl#getTypeId() */ @Override 
> public int getTypeId() { return TYPE_ID; } |
> 
> Then code like this could be written:
> 
> |switch(kobject.getTypeId()) { case AccessPattern.TYPE_ID ... case Model.TYPE_ID ... ... } |
> 
> wdyt?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/Teiid-Designer/komodo/issues/70#issuecomment-75127920>.
> 

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlTmTAQACgkQcthLMIwdEb3GowCg3Mygs+dlKoxW0ak/lO7XU3eu
VkQAoNWnr6GOsZhjj9qDNrDjyL915VyC
=mR0k
-----END PGP SIGNATURE-----

**Comment by phantomjinx** [comment]
https://github.com/Teiid-Designer/komodo/pull/72 addresses this by providing an adapts() method in WorkspaceManager.

**Comment by elvisisking** [comment]
I thought I was assigned this issue. I worked on it yesterday.

**Comment by phantomjinx** [comment]
On 20 February 2015 12:12:47 GMT, Daniel Florian <notifications@github.com> wrote:
>I thought I was assigned this issue. I worked on it yesterday.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Teiid-Designer/komodo/issues/70#issuecomment-75229133

Thats true, although I came at it from a different angle. During the deploy comand I needed to turn a kobject into a vdbb hence the adapt method.

**Comment by blafond** [comment]
https://github.com/Teiid-Designer/komodo/pull/73
