### ISSUE TITLE
Add KomodoObject validation framework

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#79]
Thinking we may want this "plugable" or adaptable to KomodoObjects. Similar to developing relational objects with getters/setters and wrapping the JCR operations, we'd maybe need a Validatable interface that might have:

public interface Validatable {
        KomodoStatus validate();
        KomodoStatus getStatus();
}

Vdb could validate it's entire contents down to the "DDL" level, or have sub-validators for Permissions, Translators, etc....

Same goes for Models... Table, View (relational structure validators). Views would delegate to SQL validator etc.

**Comment by elvisisking** [comment]
I like having the concept of a rule as the core of the framework. This in fact is at the core of Designer's validation framework. Fine-grained rules, such as checking for empty values, should facilitate reuse across the many different types of `KomodoObject`s.

So at the core of the new design are these concepts:
- rule: determines if the current state of a `KomodoObject` is valid for a specific characteristic.
- result: outcome of evaluating a rule for a given `KomodoObject`.
- rule provider: provides validation rules based on JCR node type or mixin name. Rules will be provided as an ordered collection. We can have a preference setting indicating if we should continue validation when a failure has been found. We can have as many built-in providers as we want (one for each specific relational type, one for VDB-related types, one for model-related types, or whatever). 
- rule registry: will use Java's `ServiceLoader` framework to find all the rule providers. So not only can we have our core/built-in providers, we can discover other rule providers (installed by customers, users).
- validation/build manager: can provide workspace-wide validation functions (clean, build all, etc).

Built-in rules will be evaluated before any discovered rules. Rules should be able to be overridden by rules provided non-built-in rule providers. Also, users should be able to enable/disable rules and change their result outcome level (for instance, from warning to error). The results of validation should be persisted in the repository from session to session; so a `komodo.cnd` change is necessary.

The design is not complete yet as far as the APIs go but I do have rule, result, and rule provider first-cut APIs available below for your review.

Comments welcome.

Here is the API for a rule:

```
/**
 * A rule used in validation of {@link KomodoObject}'s.
 */
public interface Rule {

    /**
     * @param kobject
     *        the object being evaluated (cannot be <code>null</code>)
     * @return the result (never <code>null</code>)
     * @throws KException
     *         if the object is not of the right type to be evaluated or if an error occurs
     */
    Result evaluate( final KomodoObject kobject ) throws KException;

    /**
     * @return the localized rule description (never empty)
     */
    String getDescription();

    /**
     * @return the unique rule identifier (never empty)
     */
    String getId();

    /**
     * @return the fully qualified JCR property names validated by this rule (never <code>null</code> but can be empty)
     */
    String[] getValidatedProperties();

    /**
     * @return the fully qualified JCR node type validated by this rule (never empty)
     */
    String getValidatedType();

    /**
     * @return <code>true</code> if rule is enabled and should be run
     */
    boolean isEnabled();

}
```

Here is the API for a result:

```
/**
 * A result of evaluating a {@link Rule validation rule}.
 */
public interface Result extends Outcome {

    /**
     * @return the path of the {@link KomodoObject} that was validated (never <code>null</code>)
     */
    String getPath();

    /**
     * @return the identifier of the rule whose evaluation produced this result (never <code>null</code>)
     */
    String getRuleId();

    /**
     * @return the date and time this result was created
     */
    long getTimestamp();

}
```

Here is the API for the rule provider:

```
/**
 * A provider for {@link KomodoObject} validation {@link Rule rules}.
 */
public interface RuleProvider {

    /**
     * Provides an ordered set of rules for the specified fully qualified JCR node type name. Rules applicable to all supertypes
     * and mixins are also be included in the result.
     *
     * @param jcrType
     *        fully qualified JCR node type name whose applicable validation rules are being requested (cannot be empty)
     * @return the applicable rules (never <code>null</code> but can be empty)
     */
    Rule[] getRules( final String jcrType );

}
```

**Comment by mdrillin** [comment]
closing - the framework has been implemented
