### ISSUE TITLE
Add KomodoObject.remove(UnitOfWork) Method

### ISSUE THREAD

**Issue by elvisisking** [Teiid-Designer/komodo#83]
Currently there is only a `removeChild` method that takes one or more names as its arguments. Since JCR allows children of the same name, when calling `removeChild` it might be possible for you to delete the wrong node. This new method will allow a node to remove itself. JCR has a similar method on `Node`.

**Comment by blafond** [comment]
https://github.com/Teiid-Designer/komodo/pull/84
