### ISSUE TITLE
Rewrite ObjectImpl.getChildrenOfType(UnitOfWork, String) To Use ObjectSearcher

### ISSUE THREAD

**Issue by elvisisking** [Teiid-Designer/komodo#89]
Currently `ObjectImpl` queries for all children and then filters out the child nodes that don't match the specified type. Instead of obtaining all children first this method should use the `ObjectSearcher` to form a query that returns only the matching children from the repository.

I tried the following but it did not work:

    final ObjectSearcher searcher = new ObjectSearcher(this.repository);
    searcher.addFromType( type );
    searcher.addWherePathClause( null, null, getAbsolutePath() );
    final List< KomodoObject > result = searcher.searchObjects( transaction );

**Comment by phantomjinx** [comment]
PR https://github.com/Teiid-Designer/komodo/pull/99
