### ISSUE TITLE
Need to override getChildren() and return empty array for any relational object that's not a "parent".

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#98]
All child-only objects like Column, Parameter, ResultSetColumn, FK, etc... need to override getChildren() and return an empty KomodoObject[] array.  This will prevent any non-relevant repo child nodes from getting exposed as true children.

This was found because a column description (Teiid ANNOTATION option value) was showing up as a child of a column

**Comment by elvisisking** [comment]
If you don't mind @phantomjinx and @blafond I would like this issue to be reassigned to me. It is related to #97 which I am assigned and am working on. I would like to role all the `getChildren`-related work into one effort. If you guys don't mind please reassign. Thanks!

**Comment by blafond** [comment]
it's ok with me if it's OK with @phantomjinx?

**Comment by phantomjinx** [comment]
On 21 April 2015 22:01:16 GMT+01:00, Barry LaFond <notifications@github.com> wrote:
>it's ok with me if it's OK with @phantomjinx?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Teiid-Designer/komodo/issues/98#issuecomment-94942638

No worries. Have sequencers to play with

**Comment by elvisisking** [comment]
I'm "going out on a limb" here and assuming you meant to reassign this to me @blafond:-) So I am re-reassigning!

**Comment by elvisisking** [comment]
Closed by #136
